image:
  repository: 610462181037.dkr.ecr.sa-east-1.amazonaws.com/public-repository
  tag: tchiotludo_akhq-0.18.0

configuration:
  akhq:
    connections:
      docker-kafka-server:
        properties:
          bootstrap.servers: "b-1.oms-dev-hlg.mehfow.c13.kafka.us-east-1.amazonaws.com:9092,b-2.oms-dev-hlg.mehfow.c13.kafka.us-east-1.amazonaws.com:9092"
        connect:
          - name: "gpa-oms-inv-kafka-connect-pool-hlg"
            url: "http://gpa-oms-inv-kafka-connect-pool-hlg.hlg.svc.cluster.local.:8083/"
        

ingress:
  enabled: false

resources:
  limits:
   cpu: 200m
   memory: 512Mi
  requests:
   cpu: 100m
   memory: 256Mi

nodeSelector:
  gpa/reserved-for: system

tolerations:
  - effect: NoSchedule
    key: gpa/reserved-for
    operator: Equal
    value: system
