# https://aka.ms/yaml
resources:
  repositories:
  - repository: templates
    type: git
    name: pipeline-templates

variables:
  registry: 610462181037.dkr.ecr.us-east-1.amazonaws.com
  repository: gpa-oms-akhq

trigger:
  batch: true
  paths:
    exclude:
      - README.md

pool: eks-oms-build-hlg

stages:
- stage: CustomCommandsBeforeBuild
  displayName: 'Custom Commands Before Build'
  jobs:
    - job: DockerLoginToECR
      steps:
        - script: 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 610462181037.dkr.ecr.us-east-1.amazonaws.com'
          displayName: 'Docker Login to ECR'

- template: ci/stages/build-docker.yml@templates
  parameters:
    registry: $(registry)
    repository: $(repository)
    region: 'sa-east-1'
    dockerfileLocation: Dockerfile
    ecrPushCustom: true

- template: ci/stages/deploy.yml@templates
  parameters:
    cluster: oms
    clusterType: eks
    releaseName: gpa-oms-akhq
    valueFile: values-{env}.yaml
    registry: $(registry)
    repository: $(repository)
    helmVersion: '3.5.1'
    timeout: '600s'
    chartValidateImage: false